server:
  port: 80

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/langmovie?serverTimezone=GMT%2B8&useSSL=false
  user: root
  password: Yan1996>

#mybatis
mybatis_config_file:   mybatis-config.xml
mybatis_mapper_path:  /mapper/**.xml
entity_package: cn.langlang.langmovie.entity

